import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CompaniesProvider } from "./ContextApi/companiesDataApi";
import { ShopProvider } from "./ContextApi/shopkeepersDataApi";
import { DataProvider } from "./ContextApi/DataContextApi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShopProvider>
        <DataProvider>
        <CompaniesProvider>
        {children}
        </CompaniesProvider>
        </DataProvider>
        </ShopProvider>
      </body>
    </html>
  );
}
