import React, { useCallback } from 'react';

const PrintButton = ({ bills, watermarkImageUrl }) => {
  const handlePrint = useCallback(() => {
    const printWindow = window.open('', '', 'width=800,height=600');

    if (printWindow) {
      printWindow.document.open();

      // Render the React component directly to the print window
      ReactDOMServer.renderToString(
        <InvoiceContent bills={bills} watermarkImageUrl={watermarkImageUrl} />
      ).then(printContent => {
        printWindow.document.write(`
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Sale Invoice</title>
              <style>
                /* Your CSS styles here (same as before) */
              </style>
            </head>
            <body>
              ${printContent}
            </body>
          </html>
        `);

        printWindow.document.close();

        printWindow.onafterprint = () => {
          printWindow.close();
        };

        printWindow.print();
      });
    } else {
      alert('Failed to open print window. Please check your browser settings.');
    }
  }, [bills, watermarkImageUrl]);

  return (
    <button onClick={handlePrint}>
      Print Invoice
    </button>
  );
};

// Create a separate component for the invoice content
const InvoiceContent = ({ bills, watermarkImageUrl }) => {
  return (
    <div className="invoice-container">
      <div className="watermark-repeat"></div>

      <div className="header">
        <h1>M.Amir Traders</h1>
        <p>Whole Sale Distributor Sugar, Ghee, Wheat etc</p>
        <p>Watkay Chowk Shadara Mingora Swat</p>
        <p>Ph#: 0341-6120696, 0946-818811</p>
      </div>

      <table className="details">
        <tr>
          <td>
            <strong>Code:</strong> 1200
          </td>
          <td>
            <strong>Invoice No:</strong> {bills.invoiceNo}
          </td>
        </tr>
        <tr>
          <td>
            <strong>Name:</strong> {bills.customerName}
          </td>
          <td>
            <strong>Date:</strong> {new Date(bills.date).toISOString().split('T')[0]}
          </td>
        </tr>
        <tr>
          <td>
            <strong>Address:</strong> {bills.address}
          </td>
          <td>
            <strong>Mob#:</strong>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Ref. Name:</strong> SWAT
          </td>
          <td>
            <strong>CNIC#:</strong>
          </td>
        </tr>
      </table>

      <table className="table-container">
        <thead>
          <tr>
            <th>Qty</th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Net Amount</th>
          </tr>
        </thead>
        <tbody>
          {bills.cart.map((item, index) => (
            <tr key={index}>
              <td>{item.quantity}</td>
              <td>{item.itemName}</td>
              <td>{item.price} PKR</td>
              <td>{item.total} PKR</td>
            </tr>
          ))}
        </tbody>
      </table>

      <table className="summary-table">
        <tr>
          <td>
            <strong>Total Amount</strong>
          </td>
          <td>{bills.totalAmount.toFixed(2)} PKR</td>
        </tr>
        <tr>
          <td>
            <strong>Discount:</strong>
          </td>
          <td>{bills.discountAmount.toFixed(2)} PKR</td>
        </tr>
        <tr>
          <td>
            <strong>Total After Discount:</strong>
          </td>
          <td>{bills.totalAfterDiscount.toFixed(2)} PKR</td>
        </tr>
        <tr>
          <td>
            <strong>Old Balance:</strong>
          </td>
          <td>{bills.oldBalance.toFixed(2)} PKR</td>
        </tr>
        <tr>
          <td>
            <strong>Net Bill Amount:</strong>
          </td>
          <td>{bills.netAmount.toFixed(2)} PKR</td>
        </tr>
        <tr>
          <td>
            <strong>Given Amount</strong>
          </td>
          <td>{bills.customerGivenAmount.toFixed(2)} PKR</td>
        </tr>
        <tr>
          <td>
            <strong>Remaining Amount</strong>
          </td>
          <td>{bills.debt.toFixed(2)} PKR</td>
        </tr>
      </table>

      <div className="signature">
        <span>
          <strong>Generated By: ___________________</strong>
        </span>
        <span>
          <strong>Store Manager: ___________________</strong>
        </span>
      </div>

      <div className="gen">
        <p style={{ marginLeft: '100px' }}>
          <strong> نوٹ</strong> مال وصول کرتے وقت اچھی طرح چیک کرلیں بعد میں کمپنی لیکیج کو کمی کی
          ذمہ دار نہ ہوگی
        </p>
        <p>
          نیز فرم کے موجودہ اور سابقہ ملازمین کو ادھار سودا یا مال کے لیے پیشگی رقم نہ دیں جس کے
          لیے ہم ذمہ دار نہ ہوں گے
        </p>
      </div>
    </div>
  );
};

import ReactDOMServer from 'react-dom/server';

export default PrintButton;